# Generated by Django 5.0.1 on 2024-04-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0005_alter_organizer_cover_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='EventsImages')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='client.category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.organizer')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('In progress', 'IP'), ('Approved', 'A'), ('Finished', 'F'), ('Denied', 'D')], default='In progress', max_length=15)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.organizer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.events')),
            ],
            options={
                'verbose_name': 'EventRequest',
                'verbose_name_plural': 'EventRequests',
            },
        ),
    ]
