# Generated by Django 5.0.1 on 2024-03-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_remove_events_duration_remove_events_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
