# Generated by Django 5.0.1 on 2024-03-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_events_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='package',
            field=models.BooleanField(default=False),
        ),
    ]
