# Generated by Django 5.0.1 on 2024-04-17 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_rename_name_customevents_company_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='ending_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
