# Generated by Django 5.0.1 on 2024-03-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_events_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
