# Generated by Django 5.0.1 on 2024-03-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_alter_events_price'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('budget', models.IntegerField()),
                ('location', models.TextField(max_length=500)),
                ('guests', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.events')),
            ],
            options={
                'verbose_name': 'EventRequest',
                'verbose_name_plural': 'EventRequests',
            },
        ),
    ]
