# Generated by Django 5.0.1 on 2024-03-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_eventrequest'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.organizer'),
            preserve_default=False,
        ),
    ]
