# Generated by Django 5.0.1 on 2024-04-04 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_events_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequest',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='status',
            field=models.CharField(choices=[('In progress', 'IP'), ('Approved', 'A'), ('Denied', 'D')], default='IP', max_length=15),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
