# Generated by Django 5.0.1 on 2024-04-04 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_remove_eventrequest_budget_and_more'),
        ('client', '0003_alter_organizer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='amount_of_people',
        ),
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='event_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.organizer'),
        ),
    ]
