# Generated by Django 5.0.1 on 2024-04-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_remove_events_amount_of_people_and_more'),
        ('client', '0003_alter_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.organizer'),
        ),
    ]
