# Generated by Django 5.0.1 on 2024-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_alter_eventrequest_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='status',
            field=models.CharField(choices=[('In progress', 'IP'), ('Approved', 'A'), ('Finished', 'F'), ('Denied', 'D')], default='In progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='events',
            name='photos',
            field=models.TextField(),
        ),
    ]
