# Generated by Django 5.0.1 on 2024-04-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_alter_eventrequest_status_alter_events_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, upload_to='EventsImages'),
        ),
    ]
