# Generated by Django 5.0.1 on 2024-04-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='photos',
            field=models.TextField(blank=True),
        ),
    ]
