# Generated by Django 5.0.1 on 2024-04-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_alter_events_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='photos',
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='EventsImages'),
        ),
    ]
