# Generated by Django 5.0.1 on 2024-04-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_organizer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='first_login',
            new_name='request_date',
        ),
        migrations.AddField(
            model_name='organizer',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='curriculum',
            field=models.FileField(blank=True, upload_to='Curriculums'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='location',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organizer',
            name='other',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='ProfilePhotos'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='status',
            field=models.CharField(choices=[('In Progress', 'IP'), ('Approved', 'A'), ('Denied', 'D')], default='In Progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='event_types',
            field=models.ManyToManyField(to='client.category'),
        ),
    ]
