# Generated by Django 5.0.1 on 2024-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_organizer_cover_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='github',
        ),
        migrations.AddField(
            model_name='organizer',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='other',
            field=models.URLField(blank=True),
        ),
    ]
